### ISSUE TITLE
The incoming event is not a valid request from Amazon API Gateway or an Application Load Balancer

### ISSUE THREAD

**Issue by balihb** [awslabs/aws-serverless-java-container#245] opened 2019-03-04 16:56 UTC
* Framework version: latest
* Implementations: Spring Boot

## Scenario
I'm trying to create two Spring Boot function. One supposed to call the other, I can call both from outside (Api Gateway), but if I try to do it directly with lambda invoke I get this:
The incoming event is not a valid request from Amazon API Gateway or an Application Load Balancer
either from code or from the lambda console.
What am I missing?
## Expected behavior
Works the same way with invoker as through api gateway.
## Actual behavior
Only works with api gateway.
## Steps to reproduce
The code is here:
https://github.com/balihb/fifi
```
./gradlew :aws:buildFibZip :aws:buildFibtimerZip
cd aws
./deploy.sh
```
## Full log output
```
93) [LambdaSandboxJava-1.0.jar:na]
	at lambdainternal.AWSLambda.<clinit>(AWSLambda.java:64) [LambdaSandboxJava-1.0.jar:na]
	at java.lang.Class.forName0(Native Method) [na:1.8.0_181]
	at java.lang.Class.forName(Class.java:348) [na:1.8.0_181]
	at lambdainternal.LambdaRTEntry.main(LambdaRTEntry.java:104) [LambdaJavaRTEntry-1.0.jar:na]

2019-03-04 15:43:35.920 ERROR 1 --- [           main] c.a.s.proxy.AwsProxyExceptionHandler     : Called exception handler for:

com.amazonaws.serverless.exceptions.InvalidRequestEventException: The incoming event is not a valid request from Amazon API Gateway or an Application Load Balancer
	at com.amazonaws.serverless.proxy.internal.servlet.AwsProxyHttpServletRequestReader.readRequest(AwsProxyHttpServletRequestReader.java:41) ~[aws-serverless-java-container-core-1.3.1.jar:na]
	at com.amazonaws.serverless.proxy.internal.servlet.AwsProxyHttpServletRequestReader.readRequest(AwsProxyHttpServletRequestReader.java:28) ~[aws-serverless-java-container-core-1.3.1.jar:na]
	at com.amazonaws.serverless.proxy.internal.LambdaContainerHandler.proxy(LambdaContainerHandler.java:174) [aws-serverless-java-container-core-1.3.1.jar:na]
	at com.amazonaws.serverless.proxy.internal.LambdaContainerHandler.proxyStream(LambdaContainerHandler.java:209) [aws-serverless-java-container-core-1.3.1.jar:na]
	at balihb.fifi.fib.aws.StreamLambdaHandler.handleRequest(StreamLambdaHandler.java:33) [task/:na]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_181]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_181]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_181]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_181]
	at lambdainternal.EventHandlerLoader$StreamMethodRequestHandler.handleRequest(EventHandlerLoader.java:350) [LambdaSandboxJava-1.0.jar:na]
	at lambdainternal.EventHandlerLoader$2.call(EventHandlerLoader.java:888) [LambdaSandboxJava-1.0.jar:na]
	at lambdainternal.AWSLambda.startRuntime(AWSLambda.java:293) [LambdaSandboxJava-1.0.jar:na]
	at lambdainternal.AWSLambda.<clinit>(AWSLambda.java:64) [LambdaSandboxJava-1.0.jar:na]
	at java.lang.Class.forName0(Native Method) [na:1.8.0_181]
	at java.lang.Class.forName(Class.java:348) [na:1.8.0_181]
	at lambdainternal.LambdaRTEntry.main(LambdaRTEntry.java:104) [LambdaJavaRTEntry-1.0.jar:na]

com.amazonaws.serverless.exceptions.InvalidRequestEventException: The incoming event is not a valid request from Amazon API Gateway or an Application Load Balancer
	at com.amazonaws.serverless.proxy.internal.servlet.AwsProxyHttpServletRequestReader.readRequest(AwsProxyHttpServletRequestReader.java:41)
	at com.amazonaws.serverless.proxy.internal.servlet.AwsProxyHttpServletRequestReader.readRequest(AwsProxyHttpServletRequestReader.java:28)
	at com.amazonaws.serverless.proxy.internal.LambdaContainerHandler.proxy(LambdaContainerHandler.java:174)
	at com.amazonaws.serverless.proxy.internal.LambdaContainerHandler.proxyStream(LambdaContainerHandler.java:209)
	at balihb.fifi.fib.aws.StreamLambdaHandler.handleRequest(StreamLambdaHandler.java:33)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at lambdainternal.EventHandlerLoader$StreamMethodRequestHandler.handleRequest(EventHandlerLoader.java:350)
	at lambdainternal.EventHandlerLoader$2.call(EventHandlerLoader.java:888)
	at lambdainternal.AWSLambda.startRuntime(AWSLambda.java:293)
	at lambdainternal.AWSLambda.<clinit>(AWSLambda.java:64)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:348)
	at lambdainternal.LambdaRTEntry.main(LambdaRTEntry.java:104)
END RequestId: 4aea4f27-70f1-458a-90fb-f5358a5e8f0f
REPORT RequestId: 4aea4f27-70f1-458a-90fb-f5358a5e8f0f	Duration: 5.94 ms	Billed Duration: 100 ms 	Memory Size: 1512 MB	Max Memory Used: 193 MB
```

**Comment by sapessi** [comment] 2019-03-04 17:41
Hey @balihb - the framework expects an event that is shaped like [an API Gateway or ALB proxy event](https://docs.aws.amazon.com/apigateway/latest/developerguide/set-up-lambda-proxy-integrations.html#api-gateway-simple-proxy-for-lambda-input-format). That doesn't mean that the call must come from API Gateway or ALB, just that the event should have the same model. If you wanted to, you could use the [`AwsProxyRequest` object](https://github.com/awslabs/aws-serverless-java-container/blob/master/aws-serverless-java-container-core/src/main/java/com/amazonaws/serverless/proxy/model/AwsProxyRequest.java) from the model package to generate the event.

If these two Lambda functions are meant to be separate services - meaning they have different scaling factors and will eventually be managed by separate teams - I'd recommend putting an actual API in-between them.

**Comment by sapessi** [comment] 2019-03-12 17:02
Can I resolve this @balihb?

**Comment by balihb** [comment] 2019-03-13 15:39
I've tried to emulate an api gateway request with AwsProxyRequest, but I haven't been able to figure out a way to access the data from the current request (so I can maybe forward it to the next request).

**Comment by sapessi** [comment] 2019-03-13 17:39
If you simply want to forward the current request to the other Lambda function you can access the incoming event from the `HttpServletRequest` as an attribute. See the [`RequestReader` code here](https://github.com/awslabs/aws-serverless-java-container/blob/master/aws-serverless-java-container-core/src/main/java/com/amazonaws/serverless/proxy/internal/servlet/AwsProxyHttpServletRequestReader.java#L53).

**Comment by sapessi** [comment] 2019-06-26 15:40
Assuming this issues is solved. Closing.

**Closed by sapessi** 2019-06-26 15:40 UTC

**Comment by thanh3d** [comment] 2019-07-12 11:03
I got the same issue, :(

**Comment by sapessi** [comment] 2019-07-15 16:43
Hi @thanh3d, what event are you trying to handle? Is it sent by an AWS service or are you calling the Lambda function directly? In general, you have two options:

1. Use the `AwsProxyRequest` object as the event for the second Lambda function. 
2. Create an alternative implementation of the `RequestReader` as described in [the wiki guide](https://github.com/awslabs/aws-serverless-java-container/wiki/Custom-event-types).

**Comment by mohit-saw** [comment] 2019-08-17 10:18
I am trying to deploy the spring boot project generated by Maven archetype for Spring Boot 2.x on AWS lambda and calling its /ping endpoint with the help of AWS API gateway but I am getting the same error reported here i.e  The incoming event is not a valid request from Amazon API Gateway or an Application Load Balancer

**Comment by sapessi** [comment] 2019-08-17 17:13
Hi @mohit-saw, make sure that you have configured API Gateway as a proxy integration. See [screenshot here](https://github.com/awslabs/aws-serverless-java-container/issues/227#issuecomment-462873409). If this is not the root cause of the issue, could you share how you deployed and configured the function + API Gateway? Did you use the SAM file?

**Comment by petrucristescu** [comment] 2020-01-16 12:47
I'm getting the same error:

`The incoming event is not a valid request from Amazon API Gateway or an Application Load Balancer`

I have the following configuration:

```

  SomeEndpoint:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: SomeCodeUri
      Handler: LambdaHandler::handleRequest
        Warmup:
          Type: Schedule
          Properties:
            Schedule: cron(0/5 8-17 ? * MON-FRI *)
```


I think a http method is expected on the request judging by what I see [here](https://github.com/awslabs/aws-serverless-java-container/blob/master/aws-serverless-java-container-core/src/main/java/com/amazonaws/serverless/proxy/internal/servlet/AwsProxyHttpServletRequestReader.java)


https://github.com/awslabs/aws-serverless-java-container/blob/master/aws-serverless-java-container-core/src/main/java/com/amazonaws/serverless/proxy/internal/servlet/AwsProxyHttpServletRequestReader.java

```

if (request.getHttpMethod() == null || request.getHttpMethod().equals("") || request.getRequestContext() == null) {
            throw new InvalidRequestEventException(INVALID_REQUEST_ERROR);
        }
```

**Comment by DogukanZengin** [comment] 2020-10-27 11:08
> I'm getting the same error:
> 
> `The incoming event is not a valid request from Amazon API Gateway or an Application Load Balancer`
> 
> I have the following configuration:
> 
> ```
>   SomeEndpoint:
>     Type: AWS::Serverless::Function
>     Properties:
>       CodeUri: SomeCodeUri
>       Handler: LambdaHandler::handleRequest
>         Warmup:
>           Type: Schedule
>           Properties:
>             Schedule: cron(0/5 8-17 ? * MON-FRI *)
> ```
> 
> I think a http method is expected on the request judging by what I see [here](https://github.com/awslabs/aws-serverless-java-container/blob/master/aws-serverless-java-container-core/src/main/java/com/amazonaws/serverless/proxy/internal/servlet/AwsProxyHttpServletRequestReader.java):
> 
> ```
> if (request.getHttpMethod() == null || request.getHttpMethod().equals("") || request.getRequestContext() == null) {
>             throw new InvalidRequestEventException(INVALID_REQUEST_ERROR);
>         }
> ```

Do we have a sample handler class for this error. This is happening because warmup plugin sends an event but it is not a gateway event. We should have a condition to return directly if the request is coming from warmup plugin.

**Comment by sapessi** [comment] 2020-10-29 17:53
Have you considered using [provisioned concurrency](https://docs.aws.amazon.com/lambda/latest/dg/configuration-concurrency.html#configuration-concurrency-provisioned) instead? Much more reliable

**Comment by petrucristescu** [comment] 2020-10-29 20:10
> > I'm getting the same error:
> > `The incoming event is not a valid request from Amazon API Gateway or an Application Load Balancer`
> > I have the following configuration:
> > ```
> >   SomeEndpoint:
> >     Type: AWS::Serverless::Function
> >     Properties:
> >       CodeUri: SomeCodeUri
> >       Handler: LambdaHandler::handleRequest
> >         Warmup:
> >           Type: Schedule
> >           Properties:
> >             Schedule: cron(0/5 8-17 ? * MON-FRI *)
> > ```
> > 
> > 
> > I think a http method is expected on the request judging by what I see [here](https://github.com/awslabs/aws-serverless-java-container/blob/master/aws-serverless-java-container-core/src/main/java/com/amazonaws/serverless/proxy/internal/servlet/AwsProxyHttpServletRequestReader.java):
> > ```
> > if (request.getHttpMethod() == null || request.getHttpMethod().equals("") || request.getRequestContext() == null) {
> >             throw new InvalidRequestEventException(INVALID_REQUEST_ERROR);
> >         }
> > ```
> 
> Do we have a sample handler class for this error? This is happening because the warmup plugin sends an event but it is not a gateway event. We should have a condition to return directly if the request is coming from warmup plugin.

It's been a while since I've played with this and I don't have the sample to provide it. Meanwhile we've dropped the warmup part.

**Comment by DogukanZengin** [comment] 2020-10-30 06:34
> > > I'm getting the same error:
> > > `The incoming event is not a valid request from Amazon API Gateway or an Application Load Balancer`
> > > I have the following configuration:
> > > ```
> > >   SomeEndpoint:
> > >     Type: AWS::Serverless::Function
> > >     Properties:
> > >       CodeUri: SomeCodeUri
> > >       Handler: LambdaHandler::handleRequest
> > >         Warmup:
> > >           Type: Schedule
> > >           Properties:
> > >             Schedule: cron(0/5 8-17 ? * MON-FRI *)
> > > ```
> > > 
> > > 
> > > I think a http method is expected on the request judging by what I see [here](https://github.com/awslabs/aws-serverless-java-container/blob/master/aws-serverless-java-container-core/src/main/java/com/amazonaws/serverless/proxy/internal/servlet/AwsProxyHttpServletRequestReader.java):
> > > ```
> > > if (request.getHttpMethod() == null || request.getHttpMethod().equals("") || request.getRequestContext() == null) {
> > >             throw new InvalidRequestEventException(INVALID_REQUEST_ERROR);
> > >         }
> > > ```
> > 
> > 
> > Do we have a sample handler class for this error? This is happening because the warmup plugin sends an event but it is not a gateway event. We should have a condition to return directly if the request is coming from warmup plugin.
> 
> It's been a while since I've played with this and I don't have the sample to provide it. Meanwhile we've dropped the warmup part.

Thanks for the answer, We have also decided to switch to provisioned concurrency

**Comment by sramaven** [comment] 2021-03-17 10:05
> Hi @mohit-saw, make sure that you have configured API Gateway as a proxy integration. See [screenshot here](https://github.com/awslabs/aws-serverless-java-container/issues/227#issuecomment-462873409). If this is not the root cause of the issue, could you share how you deployed and configured the function + API Gateway? Did you use the SAM file?

Hi, I am trying to invoke function through sam local invoke then I am facing same error, I am trying to run this through sam.yaml file

**Comment by sramaven** [comment] 2021-03-17 10:06
> > Hi @mohit-saw, make sure that you have configured API Gateway as a proxy integration. See [screenshot here](https://github.com/awslabs/aws-serverless-java-container/issues/227#issuecomment-462873409). If this is not the root cause of the issue, could you share how you deployed and configured the function + API Gateway? Did you use the SAM file?
> 
> Hi, I am trying to invoke function through sam local invoke then I am facing same error, I am trying to run this through sam.yaml file

May I get any solution
