### ISSUE TITLE
springboot2 sample not building with maven

### ISSUE THREAD

**Issue by thomashoef** [awslabs/aws-serverless-java-container#336] opened 2020-04-20 19:10 UTC
* Implementations: Spring Boot

## Scenario
I cloned the springboot2 petstore sample.

## Expected behavior
sam build builds the project correclty.

## Actual behavior

```
[INFO] Building zip: /private/var/folders/f1/7b0kkhxx3k169lx22ytcn5240000gn/T/tmpesmylcdf/target/serverless-springboot2-example-1.0-SNAPSHOT-lambda-package.zip
[INFO] 
[INFO] --- maven-install-plugin:2.5.2:install (default-install) @ serverless-springboot2-example ---
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  2.781 s
[INFO] Finished at: 2020-04-20T21:08:06+02:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-install-plugin:2.5.2:install (default-install) on project serverless-springboot2-example: The packaging for this project did not assign a file to the build artifact -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
```

## Steps to reproduce
Clone the springboot2 petstore sample.
Run sam build (without having gradle installed / removing the gradle build file)

## Full log output
see above.

**Comment by sapessi** [comment] 2020-04-20 19:13
Thanks for the report. Looks like SAM is trying to run `mvn install`. These samples are not meant to be installed, simply packaged. If you run `mvn clean package` from the sample folder, does it succeed?

I'll reach out to the SAM team.

**Comment by thomashoef** [comment] 2020-04-20 19:22
Hi,


Yes that works - but then „sam deploy“, which works fine, does not lead to a solution for my problem.
After running the deployment and calling the lambda, I still get a classnotfoundexception on the StreamHandler class… I had already built a SpringBoot2 sample myself and ran into this error - also when running sam local.
I was hoping the sample would deliver the solution…

Thanks
Thomas

Am 20.04.2020 um 21:14 schrieb Stefano Buliani <notifications@github.com<mailto:notifications@github.com>>:



Thanks for the report. Looks like SAM is trying to run mvn install. These samples are not meant to be installed, simply packaged. If you run mvn clean package from the sample folder, does it succeed?

I'll reach out to the SAM team.

**Comment by sapessi** [comment] 2020-04-21 05:44
I've pushed a fix to the samples in the master branch that should make `sam build` work, and should therefore also fix #337.

**Comment by thomashoef** [comment] 2020-04-21 08:59
Awesome Stefan, thanks for the quick fix!

Am 21.04.2020 um 07:44 schrieb Stefano Buliani <notifications@github.com<mailto:notifications@github.com>>:



I've pushed a fix to the samples in the master branch that should make sam build work, and should therefore also fix #337<https://eur03.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fawslabs%2Faws-serverless-java-container%2Fissues%2F337&data=02%7C01%7C%7Cf97d765b48b94348aae508d7e5b71f61%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637230446968394058&sdata=oO9sCayrgHaQI6bVp5WpTbKhoVM9FVGYoyDActjn4U4%3D&reserved=0>.

**Comment by thomashoef** [comment] 2020-04-21 09:25
Would there be a way to locally invoke the lambda using sam local invoke - where it does not expect an APIGateway Request in order to run successfully locally?

Thanks
Thomas

Am 21.04.2020 um 10:59 schrieb Thomas Hoefkens <thomas.hoefkens@live.de<mailto:thomas.hoefkens@live.de>>:

Awesome Stefan, thanks for the quick fix!

Am 21.04.2020 um 07:44 schrieb Stefano Buliani <notifications@github.com<mailto:notifications@github.com>>:



I've pushed a fix to the samples in the master branch that should make sam build work, and should therefore also fix #337<https://eur03.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fawslabs%2Faws-serverless-java-container%2Fissues%2F337&data=02%7C01%7C%7Cf97d765b48b94348aae508d7e5b71f61%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637230446968394058&sdata=oO9sCayrgHaQI6bVp5WpTbKhoVM9FVGYoyDActjn4U4%3D&reserved=0>.

**Comment by sapessi** [comment] 2020-04-21 22:00
@thomashoef What are you trying to do? If you just want to unit test your application then you can replicate [our tests](https://github.com/awslabs/aws-serverless-java-container/blob/master/aws-serverless-java-container-springboot2/src/test/java/com/amazonaws/serverless/proxy/spring/ServletAppTest.java#L44-L49) without going through the CLI emulator

**Comment by ggokce** [comment] 2020-10-26 08:35
Also the projects created using archetypes : com.amazonaws.serverless.archetypes and aws-serverless-springboot2-archetype  do not work .

I got  "classnotfoundexception on the StreamHandler. " The part we need to delete from pom is : 
```

 <!-- don't build a jar, we'll use the classes dir -->
                    <plugin>
                        <groupId>org.apache.maven.plugins</groupId>
                        <artifactId>maven-jar-plugin</artifactId>
                        <version>3.1.1</version>
                        <executions>
                            <execution>
                                <id>default-jar</id>
                                <phase>none</phase>
                            </execution>
                        </executions>
                    </plugin>
```

Best Regards.

**Comment by sapessi** [comment] 2020-10-26 16:00
Thanks @ggokce I'll move your report to a new issue and track it as a bug. Do you want to open it or want me to do it (you won't get notifications if I do it)

**Comment by ggokce** [comment] 2020-10-26 21:49
You are welcome... you can do it

26 Eki 2020 Pzt 17:01 tarihinde Stefano Buliani <notifications@github.com>
şunu yazdı:

**Comment by deki** [comment] 2021-01-05 19:53
Just also hit this issue with 1.5.2 and added the following to fix it:
```
                    <plugin>
                        <groupId>org.apache.maven.plugins</groupId>
                        <artifactId>maven-install-plugin</artifactId>
                        <configuration>
                            <skip>true</skip>
                        </configuration>
                    </plugin>
```

**Comment by gavvvr** [comment] 2021-02-09 07:04
Currently you will face the same error ("The packaging for this project did not assign a file to the build artifact") if you use the latest **aws-serverless-springboot2-archetype**.

How to reproduce:
- `mvn archetype:generate -DgroupId=pingapp -DartifactId=ping-service -Dversion=1.0-SNAPSHOT -DarchetypeGroupId=com.amazonaws.serverless.archetypes -DarchetypeArtifactId=aws-serverless-springboot2-archetype  -DarchetypeVersion=1.5.2`
- remove `build.gradle` from generated project files
- execute `sam build`

**Comment by deki** [comment] 2021-12-30 15:03
This should no longer happen with the latest archetype versions >=1.6. Please reopen if you still have problems.

**Comment by deki** [comment] 2022-01-06 09:39
Just noticed that https://github.com/awslabs/aws-serverless-java-container/commit/253910f3fb414844db30d22f346783d5ec48a43c only fixed the pet-store samples and not the archetypes.

Will commit a different fix that covers both.

**Closed** 2022-01-06 10:28 UTC
