### ISSUE TITLE
Spring MVC - requestDispatcher null

### ISSUE THREAD

**Issue by gmaruti** [awslabs/aws-serverless-java-container#35] opened 2017-05-14 20:01 UTC
I tried Spring MVC application with Spring boot. I have a Controller method which will forward to success /failure html page. This works fine with Spring Boot and Lambda. But I am facing Load time and Jar file size issues wirh Spring Boot.

So decided to try without Spring boot, with plain Spring using aws-serverless framework. I started getting error like "javax.servlet.ServletException: Could not get RequestDispatcher for ... ". When I looked at code, in AwsProxyServletContext the getRequestDispatcher() method is returning null. Then I realized there is no application / web server (container) is available in the package. Tried with Jetty. But couldn't get it to working (html page getting generated). Sample code is at : https://github.com/gmaruti/mvc-sample-spring.git 

Please let me know whether there any better approach!

- Thanks,

**Comment by SAPessi** [comment] 2017-05-15 15:17
Hi @gmaruti, can you share the code for your Lambda handler. This should work with both Spring and Spring Boot. To fix the jar size issue with Spring Boot you could try and shade unnecessary artifacts in maven. For example you wouldn't need Tomcat in your packaged jar.

**Comment by gmaruti** [comment] 2017-05-15 20:07
@SAPessi, i shared the link to the code base in earlier comment. Below is the link to Lambda Handler
https://github.com/gmaruti/mvc-sample-spring/blob/master/src/main/java/com/maruti/mvc_sample/LambdaHandler.java 

What I observed is apart from increasing the size of jar Spring boot is also increasing load time, more when component scan is used. To overcome, started using XML approach but as mentioned, facing issue with forwarding ( request dispatching) to html pages.

**Comment by SAPessi** [comment] 2017-05-16 15:26
@gmaruti Thanks. I replicated the issue. Looking into it.

**Comment by SAPessi** [comment] 2017-05-16 15:55
Yes, the issue is that we need to implement the `RequestDispatcher`. Changing this to enhancement. I'll work on this over the next couple of weeks.

**Comment by gmaruti** [comment] 2017-05-26 19:09
@SAPessi Any idea when this enhancement will be available.

**Comment by SAPessi** [comment] 2017-05-26 21:05
@gmaruti still working on it. Running into a few issues. I'll keep you posted here

**Comment by SAPessi** [comment] 2017-06-20 18:57
Fix for this is now merged into master. Release 0.5 will go out later today.

**Closed by SAPessi** 2017-06-20 18:57 UTC
Labels: bug, enhancement
