### ISSUE TITLE
Can't read values from property file

### ISSUE THREAD

**Issue by mpostupalski** [awslabs/aws-serverless-java-container#157] opened 2018-06-15 17:12 UTC
* Framework version: 1.1
* Implementations: Spring Boot

## Scenario

Once app is starting I want to have possibility to read values from properties file ie. application.yml. I have defined app as below:

```java
@SpringBootApplication
@ComponentScan({"foo.bar"})
public class Application extends SpringBootServletInitializer {
    @Value("${foo.clientId}")
    private String clientId;
}
```
Once app is up and running `clientId` should be populated with values provided in the file.
I have configured handler as provided in Readme file:

```java
public class StreamLambdaHandler implements RequestStreamHandler {

    private static SpringBootLambdaContainerHandler<AwsProxyRequest, AwsProxyResponse> handler;

    static {
        try {
            handler = SpringBootLambdaContainerHandler.getAwsProxyHandler(Application.class);
        } catch (ContainerInitializationException e) {
            // if we fail here. We re-throw the exception to force another cold start
            e.printStackTrace();
            throw new RuntimeException("Could not initialize Spring Boot application", e);
        }
    }

    @Override
    public void handleRequest(InputStream inputStream, OutputStream outputStream, Context context)
            throws IOException {
        handler.proxyStream(inputStream, outputStream, context);

        // just in case it wasn't closed by the mapper
        outputStream.close();
    }
}
```

## Expected behavior

Filed `clientId` populated with value from properties file

## Actual behavior

Exception during lambda start process:
`
org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'application': Injection of autowired dependencies failed; nested exception is java.lang.IllegalArgumentException: Could not resolve placeholder 'foo.clientId' in value "${foo.clientId}"
`

## Steps to reproduce

Create app as above, create properties file, put placeholders, deploy on AWS and run.

**Comment by SAPessi** [comment] 2018-06-15 18:35
Hey @mpostupalski, can you make sure that the yml file is included in the shaded jar? Let me know if it's there and I'll investigate further.

**Comment by mpostupalski** [comment] 2018-06-15 18:44
I’m pretty sure that this file is located in the jar, @SAPessi . I can retrieve values using `env.getProperty(“foo.clientId”)` syntax. So somehow file is parsed.

**Comment by mpostupalski** [comment] 2018-06-15 18:56
I found similar issue described under the link: https://stackoverflow.com/questions/36081908/using-spring-boot-cloud-with-amazon-aws-lambda-does-not-inject-values

**Comment by SAPessi** [comment] 2018-06-15 18:58
Seems plausible.  To avoid this in the future, I'll migrate the archetypes and samples to use the assembly plugin

**Comment by mpostupalski** [comment] 2018-06-15 19:11
An example with Gradle is also welcome ;-)

**Comment by mpostupalski** [comment] 2018-06-18 09:45
Ok, I found a workaround. The problem is mainly with `application.yml` file. With `application.properties` it works, but you have to provide path to the file with `PropertySource` annotation as follow:

```java
@SpringBootApplication
@ComponentScan({"foo.bar"})
@PropertySource("classpath:application.properties")
public class Application extends SpringBootServletInitializer {
...
}
```
However it doesn't work perfectly as I tried turn off a banner (`spring.main.banner-mode=off`) but it still appears in the CloudWatch logs.

**Comment by SAPessi** [comment] 2018-06-18 15:41
Does it read the yaml file is you specify it in the `@PropertySource` annotation?

**Comment by mpostupalski** [comment] 2018-06-18 20:04
Unfortunately this annotation does not work with yaml files.

**Comment by sapessi** [comment] 2018-12-22 00:58
Resolving this as a duplicate of #133. Support for both assembly and gradle will go out in version 1.3 shortly

**Closed by sapessi** 2018-12-22 00:58 UTC
