### ISSUE TITLE
ApiGatewayRequestIdentity model is incomplete

### ISSUE THREAD

**Issue by Limess** [awslabs/aws-serverless-java-container#136] opened 2018-03-15 15:36 UTC
* Framework version: 1.0
* Implementations: Jersey

## Scenario

I'm attempting to map `apiKeyId` to some stored metadata, for this I need the `apiKeyId` from the `ApiGatewayRequestIdentity` model which is injectable into 

See https://docs.aws.amazon.com/apigateway/latest/developerguide/api-gateway-mapping-template-reference.html for the full list of fields which should be available.

**Comment by SAPessi** [comment] 2018-03-15 15:44
Hey @Limess, it's not there because I couldn't see it in the documentation: https://docs.aws.amazon.com/apigateway/latest/developerguide/set-up-lambda-proxy-integrations.html#api-gateway-simple-proxy-for-lambda-input-format. There's no harm in adding the field anyway so I'll do it for the next release. Do you see it in proxy events?

**Comment by SAPessi** [comment] 2018-03-15 15:48
Yes, confirmed it is there in proxy events too - just tested. Thanks again for the report.

**Comment by Limess** [comment] 2018-03-15 15:51
Wonderful, thanks @SAPessi.

**Comment by SAPessi** [comment] 2018-03-15 15:55
Adding latest proxy structure from my test here to check the rest of the model:

```json
{
   "body":null,
   "headers":null,
   "httpMethod":"GET",
   "isBase64Encoded":false,
   "path":"/test-path",
   "pathParameters":{
      "proxy":"test-path"
   },
   "queryStringParameters":null,
   "requestContext":{
      "accountId":"XXXXXXXXX",
      "apiId":"xxxxxxxxx",
      "httpMethod":"GET",
      "identity":{
         "accessKey":"XXXXXXXXXXXXXXXXXXX",
         "accountId":"XXXXXXXXX",
         "apiKey":"test-invoke-api-key",
         "apiKeyId":"test-invoke-api-key-id",
         "caller":"XXXXXXXXXXXXXXX",
         "cognitoAuthenticationProvider":null,
         "cognitoAuthenticationType":null,
         "cognitoIdentityId":null,
         "cognitoIdentityPoolId":null,
         "sourceIp":"test-invoke-source-ip",
         "user":"AIDAISOZ5QV4MZSUGZEUK",
         "userAgent":"Apache-HttpClient/4.5.x (Java/1.8.0_144)",
         "userArn":"arn:aws:iam::XXXXXXXXXXXX:user/admin"
      },
      "path":"/{proxy+}",
      "requestId":"test-invoke-request",
      "resourceId":"ryjeap",
      "resourcePath":"/{proxy+}",
      "stage":"test-invoke-stage"
   },
   "resource":"/{proxy+}",
   "stageVariables":null
}
```

**Comment by SAPessi** [comment] 2018-04-06 17:09
Latest merge includes the new fields. Closing this issue.

**Closed by SAPessi** 2018-04-06 17:09 UTC
Labels: bug
