### ISSUE TITLE
NoClassDefFoundError returned by lambda after upgrading to version 1.0

### ISSUE THREAD

**Issue by alepeltier** [awslabs/aws-serverless-java-container#135] opened 2018-03-12 11:23 UTC
* Framework version: 1.0
* Implementations: Jersey / Jackson / Jetty

I've recently upgraded from version 0.8 to 1.0. I noticed that some of the files have moved so I re-imported them into my project. The code works perfectly when I run it locally however when i upload the jar to a Lambda I get the following error:

`{
  "errorMessage": "org/glassfish/jersey/internal/inject/AbstractBinder",
  "errorType": "java.lang.NoClassDefFoundError"
}`

This is the log from the lambda:

```
START RequestId: 54fc27d0-25e5-11e8-8aa7-f108797e428d Version: $LATEST
org/glassfish/jersey/internal/inject/AbstractBinder: java.lang.NoClassDefFoundError
java.lang.NoClassDefFoundError: org/glassfish/jersey/internal/inject/AbstractBinder
        at java.lang.ClassLoader.defineClass1(Native Method)
        at java.lang.ClassLoader.defineClass(ClassLoader.java:763)
        at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
        at java.net.URLClassLoader.defineClass(URLClassLoader.java:467)
        at java.net.URLClassLoader.access$100(URLClassLoader.java:73)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:368)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:362)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.net.URLClassLoader.findClass(URLClassLoader.java:361)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
        at com.amazonaws.serverless.proxy.jersey.JerseyLambdaContainerHandler.<init>(JerseyLambdaContainerHandler.java:139)
        at com.amazonaws.serverless.proxy.jersey.JerseyLambdaContainerHandler.getAwsProxyHandler(JerseyLambdaContainerHandler.java:101)
        at dashboard.ApplicationHandler.<init>(ApplicationHandler.java:23)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
Caused by: java.lang.ClassNotFoundException: org.glassfish.jersey.internal.inject.AbstractBinder
        at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
        ... 18 more

END RequestId: 54fc27d0-25e5-11e8-8aa7-f108797e428d
REPORT RequestId: 54fc27d0-25e5-11e8-8aa7-f108797e428d  Duration: 0.62 ms       Billed Duration: 100 ms         Memory Size: 1536 MB    Max Memory Used: 55 MB 
```

Have I missed something which should be included ?

**Comment by SAPessi** [comment] 2018-03-12 15:48
Hey @alepeltier,

This could be caused by the Jersey upgrade. In version 1.0 of the library, we moved to Jersey 2.26. In the latest version, Jersey does not package its dependency injection mechanism. You may need to manually add the hk2 dependency:

```xml
<dependency>
   <groupId>org.glassfish.jersey.inject</groupId>
   <artifactId>jersey-hk2</artifactId>
   <version>2.26</version>
</dependency>
```

**Comment by alepeltier** [comment] 2018-03-13 09:00
Hey @SAPessi 

I've updated the following dependencies but still get the error.

`    <dependency>
            <groupId>org.glassfish.jersey.inject</groupId>
            <artifactId>jersey-hk2</artifactId>
            <version>2.26</version>
        </dependency>`

` <dependency>
            <groupId>com.amazonaws.serverless</groupId>
            <artifactId>aws-serverless-java-container-jersey</artifactId>
            <version>1.0</version>
            <exclusions>
                <exclusion>
                    <artifactId>jcl-over-slf4j</artifactId>
                    <groupId>org.slf4j</groupId>
                </exclusion>
                <exclusion>
                    <artifactId>slf4j-api</artifactId>
                    <groupId>org.slf4j</groupId>
                </exclusion>
            </exclusions>
        </dependency>`

Are there anyother dependencies used ? I can send you the POM file if needed.

**Comment by SAPessi** [comment] 2018-03-13 15:14
Are you injecting any of the servlet objects? We've changed the injection method to use `Suppliers`, these are automatically registered if your `Application` object is of type `ResourceConfig`, otherwise you'll have to do it manually: [source code](https://github.com/awslabs/aws-serverless-java-container/blob/master/aws-serverless-java-container-jersey/src/main/java/com/amazonaws/serverless/proxy/jersey/JerseyLambdaContainerHandler.java#L138).

Also, make sure that all jersey packages you include are version 2.26.

If neither of these things are the issue, I may need your `pom.xml` to try and replicate.

**Comment by alepeltier** [comment] 2018-03-14 18:12
@SAPessi  on the bright side i'm now getting a different error.

`{
  "errorMessage": "org/apache/commons/io/input/NullInputStream",
  "errorType": "java.lang.NoClassDefFoundError",
  "stackTrace": [
    "com.amazonaws.serverless.proxy.internal.servlet.AwsProxyHttpServletRequestReader.readRequest(AwsProxyHttpServletRequestReader.java:37)",
    "com.amazonaws.serverless.proxy.internal.servlet.AwsProxyHttpServletRequestReader.readRequest(AwsProxyHttpServletRequestReader.java:27)",
    "com.amazonaws.serverless.proxy.internal.LambdaContainerHandler.proxy(LambdaContainerHandler.java:160)",
    "dvsa.dashboard.ApplicationHandler.handleRequest(ApplicationHandler.java:34)",
    "dvsa.dashboard.ApplicationHandler.handleRequest(ApplicationHandler.java:12)"
  ],
  "cause": {
    "errorMessage": "org.apache.commons.io.input.NullInputStream",
    "errorType": "java.lang.ClassNotFoundException",
    "stackTrace": [
      "java.net.URLClassLoader.findClass(URLClassLoader.java:381)",
      "java.lang.ClassLoader.loadClass(ClassLoader.java:424)",
      "java.lang.ClassLoader.loadClass(ClassLoader.java:357)",
      "com.amazonaws.serverless.proxy.internal.servlet.AwsProxyHttpServletRequestReader.readRequest(AwsProxyHttpServletRequestReader.java:37)",
      "com.amazonaws.serverless.proxy.internal.servlet.AwsProxyHttpServletRequestReader.readRequest(AwsProxyHttpServletRequestReader.java:27)",
      "com.amazonaws.serverless.proxy.internal.LambdaContainerHandler.proxy(LambdaContainerHandler.java:160)",
      "dvsa.dashboard.ApplicationHandler.handleRequest(ApplicationHandler.java:34)",
      "dvsa.dashboard.ApplicationHandler.handleRequest(ApplicationHandler.java:12)"
    ]
  }
}`


This is my application handler:

`import com.amazonaws.serverless.proxy.jersey.JerseyLambdaContainerHandler;
import com.amazonaws.serverless.proxy.model.AwsProxyRequest;
import com.amazonaws.serverless.proxy.model.AwsProxyResponse;
import com.amazonaws.services.lambda.runtime.Context;
import com.amazonaws.services.lambda.runtime.RequestHandler;
import org.glassfish.jersey.jackson.JacksonFeature;
import org.glassfish.jersey.server.ResourceConfig;
import org.glassfish.jersey.server.ServerProperties;

public class ApplicationHandler implements RequestHandler<AwsProxyRequest, AwsProxyResponse> {
    private ResourceConfig jerseyApplication = new ResourceConfig()
            .packages("dashboard")
            .property(ServerProperties.BV_SEND_ERROR_IN_RESPONSE, true)
            .property(ServerProperties.BV_DISABLE_VALIDATE_ON_EXECUTABLE_OVERRIDE_CHECK, true)
            .register(JacksonFeature.class)
            .register(DashboardResponse.class)
            .register(AuthenticationFilter.class);

    private JerseyLambdaContainerHandler<AwsProxyRequest, AwsProxyResponse> handler
            = JerseyLambdaContainerHandler.getAwsProxyHandler(jerseyApplication);

    /**
     * This lambda function doesn't call any methods it instead calls the jersey config which determines which methods
     * will be called.
     *
     * @param awsProxyRequest AwsProxyRequest
     * @param context         Context
     * @return JerseyLambdaContainerHandler
     */
    @Override
    public AwsProxyResponse handleRequest(AwsProxyRequest awsProxyRequest, Context context) {
        return handler.proxy(awsProxyRequest, context);
    }
}
`

This all looks standard to me. Is there anything here which could cause that error to be thrown it appears to be coming from the AwsProxyResponse method.

**Comment by SAPessi** [comment] 2018-03-15 16:20
Hey @alepeltier, the use of `NullInputStream` is new to the [latest version of the library](https://github.com/awslabs/aws-serverless-java-container/blob/master/aws-serverless-java-container-core/src/main/java/com/amazonaws/serverless/proxy/internal/servlet/AwsProxyHttpServletRequest.java#L406). The `NullInputStream` object is defined in the `commons-io` package, which for me is imported by the [`commons-fileupload` dependency](https://github.com/awslabs/aws-serverless-java-container/blob/master/aws-serverless-java-container-core/pom.xml#L53). Are you also importing a version of `commons-io`? Perhaps there is a conflict where your version does not contain the `NullInputStream` object.

One more note, I would recommend switching to the [stream handler](https://github.com/awslabs/aws-serverless-java-container/blob/master/samples/jersey/pet-store/src/main/java/com/amazonaws/serverless/sample/jersey/StreamLambdaHandler.java) - allows the library to unmarshal Cognito-related fields and use annotations in general.

**Comment by alepeltier** [comment] 2018-03-17 15:06
Hello @SAPessi,

You're right it was the commons-io package I was excluding it from the jar. 

Thank you for all your help.

**Comment by alepeltier** [comment] 2018-04-03 09:34
@SAPessi  

I think it might be worth mentioning that you can't excude this package from the Jar.

**Comment by alepeltier** [comment] 2018-04-03 09:54
Also sorry for the slow reply I've been on holiday and didn't have access to my laptop

**Comment by SAPessi** [comment] 2018-04-06 17:08
I'll look into adding that to the docs. Closing this issue for now.

**Closed by SAPessi** 2018-04-06 17:08 UTC
