### ISSUE TITLE
AwsProxyServletContext Does Not Support Servlet Filter Registration

### ISSUE THREAD

**Issue by blakeney** [awslabs/aws-serverless-java-container#15] opened 2017-03-07 22:16 UTC
Hello,

I am trying to use this library along with Spring Boot to create a REST application that uses `javax.servlet.Filter` implementations to transform responses.  I see that all of the filter-related methods in `AwsProxyServletContext` are overridden to simply return `null` or to do nothing ([source](https://github.com/awslabs/aws-serverless-java-container/blob/master/aws-serverless-java-container-core/src/main/java/com/amazonaws/serverless/proxy/internal/servlet/AwsProxyServletContext.java#L306-L339)).  This would seem to indicate that `Filter`s are not supported with this container.  Is that correct?

I have attempted several methods of registering `Filter`s, which work properly with my local tests, but do not seem to have any effect when running in a live Lambda.

If I cannot use `Filter`, I will try to use Spring's `HandlerInterceptor` mechanism instead.

**Comment by blakeney** [comment] 2017-03-08 17:29
I did some more investigation and determined with more certainty that indeed, the current implementation does not support Filter registration (or Servlet registration, for that matter).  I also determined that `HandlerInterceptor`s will not serve my particular need, so I am just going to work around this in the `handleRequest` method of my own project for the time being, essentially bypassing Spring for part of my code.

I probably will not have time to patch this library to add Filter support myself any time soon, so unfortunately I can't offer a Pull Request at the moment.  I'll leave the ticket open for now in case anyone else is interested in this as a feature, but I'm also okay with it if this is a "Won't Fix."  Thanks!

**Comment by SAPessi** [comment] 2017-03-08 22:11
Correct, at the moment it does not. I'd be interested to take a look at your filter code and see if/how we can add support for it. Anything you can share on GitHub or here?

**Comment by AlainJanssens** [comment] 2017-03-13 08:55
Is this also the reason why '@Valid' isn't working?

**Comment by SAPessi** [comment] 2017-03-13 16:02
I'm no spring expert but doing some research I can see that the `@Valid` annotation does run as a filter. We are currently designing filters support based on this issue and we'll have something in a branch over the next few weeks.

**Comment by AlainJanssens** [comment] 2017-03-13 16:04
Thanks for the answer @SAPessi ..

I created a separated issue for this...

**Comment by SAPessi** [comment] 2017-03-13 16:07
I'll keep that issue open until I can confirm for certain that this is the cause of the issue. If it is, then I'll close the separate issue and group everything in here. Otherwise we'll address it there.

**Comment by SAPessi** [comment] 2017-03-22 22:56
Hey @blakeney, could you share some sample code on how you initialize (and add) filters in your spring application?

**Comment by SAPessi** [comment] 2017-03-23 23:51
I've pushed a first version of the filter support to the servlet-improvements branch. This is the commit https://github.com/awslabs/aws-serverless-java-container/commit/d7bec0a06a4d241a6ef150fbaba733d74cde13ad. You can register filters with the setStartupHandler lambda:

```java
try {
    handler = SpringLambdaContainerHandler.getAwsProxyHandler(EchoSpringAppConfig.class);
    handler.setStartupHandler(c -> {
        FilterRegistration.Dynamic registration = c.addFilter("CustomHeaderFilter", CustomHeaderFilter.class);
        // update the registration to map to a path
        registration.addMappingForUrlPatterns(EnumSet.of(DispatcherType.REQUEST), true, "/*");
        // servlet name mappings are disabled and will throw an exception
    });
} catch (ContainerInitializationException e) {
    e.printStackTrace();
}
```

Next I will work on supporting the filter annotations.

**Comment by SAPessi** [comment] 2017-04-13 21:01
Version 0.4 is out and adds support for servlet filter:

```java
handler.setStartupHandler(c -> {
    FilterRegistration.Dynamic registration = c.addFilter("CustomHeaderFilter", CustomHeaderFilter.class);
    // update the registration to map to a path
    registration.addMappingForUrlPatterns(EnumSet.of(DispatcherType.REQUEST), true, "/*");
    // servlet name mappings are disabled and will throw an exception
});
```

Closing this issue.

**Closed by SAPessi** 2017-04-13 21:01 UTC
Labels: enhancement
