### ISSUE TITLE
Allow (or delegate to) other dispatcherServlets

### ISSUE THREAD

**Issue by otbe** [awslabs/aws-serverless-java-container#252] opened 2019-04-09 11:50 UTC
* Framework version: 1.3.1
* Implementations: Spring Boot

## Scenario
Use another servlet besides `dispactherServlet`.
Basically this issue is the same as #196  but was closed without a working solution. I want to deploy the same graphql-java `SimpleGraphQLHttpServlet ` which throws "Only dispatcherServlet is supported". 

## Expected behavior
It should somehow work :)

I already tried to register a `ServletRegistrationBean` but my compiler screams at me because the constructor of SimpleGraphQLServlet is private. is there any other way to get around this?

**Comment by sapessi** [comment] 2019-04-09 17:07
Hi @otbe - I'll try to replicate the issue and see if I can find a good generic solution for it. Do you have a project you could share so that I don't have to start from scratch?

**Comment by otbe** [comment] 2019-04-09 17:23
Hi @sapessi 

thanks for your response. You can use my little playground repo if you want: https://github.com/otbe/kotlin-sb-aws-lambda

You should be able to deploy a version by running:

```
$ mvn install
$ sls deploy 
```
`sls` aka serverless must be global available (`$ yarn global add serverless`)

After that you should be able to query the API by using this curl snippet:
```
curl 'https://<API_URL>/dev/graphql' -H 'accept-encoding: gzip, deflate' -H 'content-type: application/json' -H 'accept: application/json'  --data-binary '{"query":"{\n  snacks {\n    id\n  }\n}\n","variables":{}}' --compressed
```

thank you!

**Comment by sapessi** [comment] 2019-09-12 02:46
In order to solve #239 we have added a more complete implementation of the ServletContext that can register Servlets and associate paths to them. We have also simplified the SpringBoot integration to simply act as an embedded server. Can I ask you to test the application with version `1.4-SNAPSHOT` of the library from the `core` branch of this repo @otbe. You can follow the instructions in [my last comment in the issue](https://github.com/awslabs/aws-serverless-java-container/issues/239#issuecomment-530537925) to test.

**Comment by sapessi** [comment] 2019-09-23 18:53
Hi @otbe, I've tested your code with release 1.4-SNAPSHOT (referenced in the other issue). It seems to load fine. However, the graphql library you are using requires WebSocket which is not supported today through this library. It's something we have planned for release 2.0 (#277). I'll consider the root cause of this issue solved (we can register the new servlet) and add your +1 to WebSocket support

**Comment by sapessi** [comment] 2019-09-30 15:33
Release 1.4 is out on maven central. The [release notes](https://github.com/awslabs/aws-serverless-java-container/releases/tag/aws-serverless-java-container-1.4) include a list of all the changes. Closing this issue.

**Closed by sapessi** 2019-09-30 15:33 UTC
Labels: enhancement
