### ISSUE TITLE
Unable to config @Valid for bean validation in spring

### ISSUE THREAD

**Issue by AlainJanssens** [awslabs/aws-serverless-java-container#16] opened 2017-03-13 16:01 UTC
If you annotate your project with @EnableWebMvc and you add the hibernate-validator to your classpath, you should be able to use @Valid in your controller to validate the annotated bean...

Unfortunately this is not working... 

Any idea why, or a workaround?

Regards

**Comment by SAPessi** [comment] 2017-03-13 16:08
We are investigating whether this is caused by #15.

**Comment by SAPessi** [comment] 2017-03-23 23:52
I have an update on filters posted on #15

**Comment by SAPessi** [comment] 2017-03-24 21:39
@AlainJanssens can you paste here some sample code on how you use `@Valid` (both init and runtime) so that I can include it in a unit test?

**Comment by SAPessi** [comment] 2017-03-28 17:56
Turns out this is not caused by #15. I have looked into this and managed to get the `@Valid` annotation working. I've added a unit test for this in the new branch

Few things to do:

1. declare your config as an `AnnotationConfigWebApplicationContext`:
```java
@Configuration
@ComponentScan("com.amazonaws.serverless.proxy.spring.echoapp")
public class EchoSpringAppConfig {

    @Autowired
    private AnnotationConfigWebApplicationContext applicationContext;

    @Bean
    public SpringLambdaContainerHandler springLambdaContainerHandler() throws ContainerInitializationException {
        SpringLambdaContainerHandler handler = SpringLambdaContainerHandler.getAwsProxyHandler(applicationContext);
        handler.setRefreshContext(false);
        return handler;
    }

    @Bean
    public ObjectMapper objectMapper() {
        return new ObjectMapper();
    }

    @Bean
    public MockLambdaContext lambdaContext() {
        return new MockLambdaContext();
    }

    @Bean
    public javax.validation.Validator localValidatorFactoryBean() {
        return new LocalValidatorFactoryBean();
    }
}
```

2. Add the required dependencies in the pom.xml file:
```
<dependency>
  <groupId>org.hibernate</groupId>
  <artifactId>hibernate-validator</artifactId>
  <version>5.4.1.Final</version>
  <scope>test</scope>
</dependency>
<dependency>
  <groupId>javax.el</groupId>
  <artifactId>javax.el-api</artifactId>
  <version>2.2.4</version>
</dependency>
<dependency>
  <groupId>org.glassfish.web</groupId>
  <artifactId>javax.el</artifactId>
  <version>2.2.4</version>
</dependency>
```

3. Use the `@Valid` annotation in your method.
```java
@RequestMapping(path = "/user", method=RequestMethod.POST, consumes = MediaType.APPLICATION_JSON)
    public ResponseEntity<ValidatedUserModel> createUser(@Valid @RequestBody ValidatedUserModel newUser, BindingResult results) {
...
```

**Comment by SAPessi** [comment] 2017-03-28 17:56
Switched to help wanted tag and closing the issue.

**Closed by SAPessi** 2017-03-28 17:56 UTC
Labels: help wanted
