### ISSUE TITLE
Change method naming of AwsProxyRequest for Jackson and other serializers.

### ISSUE THREAD

**Issue by MarvGilb** [awslabs/aws-serverless-java-container#262] opened 2019-06-14 09:56 UTC
Serializer like Jackson's ObjectMapper are using method names for serialization and deserialization. 
Prefixes like get/set/is will be removed and the following String will be used as parameter names.

For the property _isBase64Encoded_ the method names are:

- isBase64Encoded
- setIsBase64Encoded

See: https://github.com/awslabs/aws-serverless-java-container/blob/e4f4d4de6016a60d3fe728181d24aa4d91e645ec/aws-serverless-java-container-core/src/main/java/com/amazonaws/serverless/proxy/model/AwsProxyRequest.java#L171

This leads to a serialization of
`{
  "base64Encoded"
}` 
which can not be deserialized because the expected value name is: **isBase64Encoded**

Please rename the getter to **getIsBase64Encoded** or **isIsBase64Encoded**, so that the property is serialized as:
`{
  "isBase64Encoded"
}`

**Comment by Marclev78** [comment] 2019-06-18 12:45
This should be treated as a high priority as it is causing requests to `sam local start-api` to consistently to fail with an InternalServerError when trying to deserialise the response.

**Comment by sapessi** [comment] 2019-06-18 16:37
Thanks for the feedback @Marclev78 - I'll work to replicate and push a fix with the next patch release. Hoping to get it out this week.

**Comment by sapessi** [comment] 2019-06-20 15:56
Hey @Marclev78, I have a fix for this about to go out in the core branch. However, I doubt this is the cause of your issue. Requests are only de-serialized, which happens correctly, the framework never serializes them. Still, I have added the annotation on the field [like we do in the response](https://github.com/awslabs/aws-serverless-java-container/blob/master/aws-serverless-java-container-core/src/main/java/com/amazonaws/serverless/proxy/model/AwsProxyResponse.java#L122) to make sure this happens correctly. 

Can you share a stack trace of what is happening with SAM local so that we can figure out what the root cause of the issue is?

**Comment by sapessi** [comment] 2019-06-27 22:25
[Release 1.3.2](https://github.com/awslabs/aws-serverless-java-container/releases/tag/aws-serverless-java-container-1.3.2) - which includes this fix - is on its way to maven central! Resolving this issue.

**Closed by sapessi** 2019-06-27 22:25 UTC
Labels: bug

**Comment by gakinson** [comment] 2019-09-26 23:32
I am experiencing this issue using the latest 1.3.2 version.

**Comment by sapessi** [comment] 2019-09-27 05:16
Hi @gakinson, the annotation is definitely there in the latest release ([code](https://github.com/awslabs/aws-serverless-java-container/blob/master/aws-serverless-java-container-core/src/main/java/com/amazonaws/serverless/proxy/model/AwsProxyResponse.java#L122)). 

I suspect your issue may be caused by the fact that you are using the typed handler rather than the stream one: The typed handler (receives a proxy event + context and returns a proxy response) uses Lambda's built-in serialization mechanism which does not read/use annotations. I would recommend switching to the stream handler (see [the examples](https://github.com/awslabs/aws-serverless-java-container/blob/master/samples/jersey/pet-store/src/main/java/com/amazonaws/serverless/sample/jersey/StreamLambdaHandler.java#L20-L33)). The stream handler uses the object mapper included in this framework which will respect the annotations.

**Comment by gakinson** [comment] 2019-09-27 17:54
Hello @sapessi ,

Thanks for the prompt response. I can switch to use that to test, but I also just created a new instance of a jackson ObjectMapper which should respect annotations, I think, but it still does not do the deserialization correctly.

Thank you,
Geoffrey K

**Comment by gakinson** [comment] 2019-09-27 17:57
Here is my post from thread https://github.com/awslabs/aws-sam-cli/issues/1193 :

Hello, here are my notes on how I could get it working by duplicating your class and playing around with annotations.


### Failed attempts
1. Move the @JsonProperty annotation to the field and removing it from the "is" getter
2. Tried add additional letters tot he prefix

### Successful attempts
1. Deleting the "isBase64Encoded()" and putting JsonProperty("isBase64Encoded") to the field isBase64Encoded
  - Issue with this is that there is no getter now.
2. Rename the "isBase64Encoded()" function to "getIsBase64Encoded()"


Still trying some others that are backwards compatible, but please address this in some way.

**Comment by gakinson** [comment] 2019-09-27 18:53
@sapessi 

I have tried this using RequestStreamHandler and it all works. I read a little more regarding RequestHandler and I see now. 

Thanks for your patience.

**Comment by sapessi** [comment] 2019-09-27 18:55
Great! Apologies for missing your earlier messages @gakinson

**Comment by gakinson** [comment] 2019-09-27 18:59
> Great! Apologies for missing your earlier messages @gakinson

To see if I figured it out, I think the reason why annotations is ignored is because your lambda container object mapper is using the [AfterBurner](https://github.com/FasterXML/jackson-modules-base/tree/master/afterburner) module?

**Comment by sapessi** [comment] 2019-09-27 19:04
When you use a typed handler (`RequestHandler<AwsProxyRequest, AwsProxyResponse>`) the event and output are marshalled/unmarshalled by `AWS Lambda`, it is outside of Serverless Java Container's control. The Lambda Java runtime is configured to ignore annotations altogether. That's why it doesn't pick them up no matter what.

**Comment by kastork** [comment] 2020-09-27 21:16
What's odd is, when running `sam local` you get the `base64Encoded` field, but when deploying to lambda/api-gatway you get `isBase64Encoded`.

This is using 1.3.2 and the typed handler.

**Comment by sapessi** [comment] 2020-09-29 19:54
Which Lambda runtime are you using @kastork? `java8`, `java8.al2`, or `java11`?

**Comment by kastork** [comment] 2020-09-30 15:17
@sapessi   I'm using java11

**Comment by kastork** [comment] 2020-09-30 15:34
@sapessi Because of your question, I tried it with `java8` and `java8.al2`. The results are the same locally.

**Comment by kristofvb** [comment] 2020-12-19 13:54
@sapessi This really is a problem with class `AwsProxyResponse`. The getter/setter pair should really be getIsBase64Encoded/setIsBase64Encoded. As you said the Lambda Java runtime will not take into account the added Jackson annotation. The correct lambda response format is documented [here](https://docs.aws.amazon.com/apigateway/latest/developerguide/set-up-lambda-proxy-integrations.html#api-gateway-simple-proxy-for-lambda-output-format).

Also, as can be seen in the linked issue for SAM CLI, this tool is totally unforgiving in handling responses with the wrong property `base64Encoded`.

Would you be willing to provide both properties `base64Encoded` and `isBase64Encoded` in the response (by having two pairs of getter/setter methods)?
