### ISSUE TITLE
ApplicationContextException: Unable to start ServletWebServerApplicationContext

### ISSUE THREAD

**Issue by boroda4436** [awslabs/aws-serverless-java-container#326] opened 2020-02-26 14:12 UTC
* Framework version: aws-cli/2.0.0dev4 Python/3.7.4 Darwin/19.2.0 botocore/2.0.0dev3
* Implementations: Spring Boot

## Scenario
Run the spring-boot2 app locally

## Expected behavior
the app starts without exceptions

## Actual behavior
error happens:

![image](https://user-images.githubusercontent.com/13794896/75352475-78a93700-58b2-11ea-924c-92aaa85d3e55.png)

## Steps to reproduce
1. Download the repo
2. cd samples/springboot2/pet-store
3. Run com.amazonaws.serverless.sample.springboot2.Application from your IDE as a simple spring-boot app.

## Full log output
2020-02-26 15:57:01.303  INFO 59255 --- [           main] c.a.s.sample.springboot2.Application     : Starting Application on Bogdans-MBP.mate.academy with PID 59255 (/Users/bchupika/IdeaProjects/Study/aws-serverless-java-container/samples/springboot2/pet-store/target/classes started by bchupika in /Users/bchupika/IdeaProjects/Study/aws-serverless-java-container)
2020-02-26 15:57:01.312  INFO 59255 --- [           main] c.a.s.sample.springboot2.Application     : No active profile set, falling back to default profiles: default
2020-02-26 15:57:02.082 ERROR 59255 --- [           main] o.s.boot.SpringApplication               : Application run failed

org.springframework.context.ApplicationContextException: Unable to start web server; nested exception is org.springframework.context.ApplicationContextException: Unable to start ServletWebServerApplicationContext due to missing ServletWebServerFactory bean.
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.onRefresh(ServletWebServerApplicationContext.java:156)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:543)
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:141)
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:744)
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:391)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:312)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1215)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1204)
	at com.amazonaws.serverless.sample.springboot2.Application.main(Application.java:47)
Caused by: org.springframework.context.ApplicationContextException: Unable to start ServletWebServerApplicationContext due to missing ServletWebServerFactory bean.
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.getWebServerFactory(ServletWebServerApplicationContext.java:203)
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.createWebServer(ServletWebServerApplicationContext.java:179)
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.onRefresh(ServletWebServerApplicationContext.java:153)
	... 8 common frames omitted

Process finished with exit code 1

**Comment by sapessi** [comment] 2020-02-27 16:10
This is probably cause by the fact that we [explicitly exclude](https://github.com/awslabs/aws-serverless-java-container/blob/master/samples/springboot2/pet-store/pom.xml#L25-L30) the embedded Tomcat that implements `ServletWebServerFactory`.

To solve this, we could remove the exclusion from the dependency and simply shade Tomcat out when producing a build for AWS Lambda. Would that help?

**Comment by sapessi** [comment] 2020-03-31 04:13
@boroda4436 I found the root cause and committed a fix in the `v1.5` branch. We'll have this out with the next release shortly. I have also added a new feature to the builder that allows you to specify whether you want to start a `WebApplicationType.SERVLET`: [Test sample](https://github.com/awslabs/aws-serverless-java-container/blob/v1.5/aws-serverless-java-container-springboot2/src/test/java/com/amazonaws/serverless/proxy/spring/servletapp/LambdaHandler.java#L21)

**Closed** 2020-04-08 17:57 UTC
Labels: enhancement

**Comment by jchambers** [comment] 2020-04-16 17:03
Hi! I'm afraid I'm still having this problem even after the 1.5 release. I created a new project with:

```
mvn archetype:generate -DgroupId=my.service -DartifactId=my-service -Dversion=1.0-SNAPSHOT \
       -DarchetypeGroupId=com.amazonaws.serverless.archetypes \
       -DarchetypeArtifactId=aws-serverless-springboot2-archetype \
       -DarchetypeVersion=1.5
```

Attempting to start the included `Application` either through an IDE or via Maven produces the same problem.

**Comment by sapessi** [comment] 2020-04-16 18:33
The archetype by default excludes the embedded Tomcat since it is not useful in Lambda - this is why Spring can't find an implementation of ServletWebServerFactory. You can just uncomment the exclusion from the pom file:

```xml
<dependency>
   <groupId>org.springframework.boot</groupId>
   <artifactId>spring-boot-starter-web</artifactId>
   <!--exclusions>
       <exclusion>
           <groupId>org.springframework.boot</groupId>
           <artifactId>spring-boot-starter-tomcat</artifactId>
        </exclusion>
    </exclusions-->
</dependency>
```

Fair point though. I'll create a separate issue to track moving this into a profile for the next release

**Comment by jchambers** [comment] 2020-04-16 23:37
It's true that removing that exclusion eliminates the exception, but the Spring Boot application still doesn't start up all the way; instead, it appears to hang shortly after displaying the Spring Boot banner. I think there may be something else at play.

**Comment by jchambers** [comment] 2020-04-16 23:44
I was mistaken, and I apologize for the false alarm; I missed that the default logging level for the project is `WARN`, and so all of the usual startup messages (at `INFO` or lower) weren't displayed. Everything is working as expected.

**Comment by sapessi** [comment] 2020-04-17 04:14
No worries. For the next release, we'll make sure to include the correct profiles in the archetypes.

**Comment by bbehling** [comment] 2020-05-01 23:04
I'm using version 1.5 and still need to comment out the exclusions. Was 1.5 supposed to include a fix where we didn't have to comment that out?

**Comment by SaptarshiMisra** [comment] 2021-01-04 19:43
I'm using version 1.5. Getting this error. Could you please share some thoughts

```
java.lang.NoClassDefFoundError: org/springframework/boot/WebApplicationType
	at com.amazonaws.serverless.proxy.spring.SpringBootProxyHandlerBuilder.<init>(SpringBootProxyHandlerBuilder.java:32)
	at com.amazonaws.serverless.proxy.spring.SpringBootLambdaContainerHandler.getAwsProxyHandler(SpringBootLambdaContainerHandler.java:88)
	at com.inboxy.api.StreamLambdaHandler.<clinit>(StreamLambdaHandler.java:20)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:348)
Caused by: java.lang.ClassNotFoundException: org.springframework.boot.WebApplicationType
	at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 5 more
```

**Comment by SamnnyWong** [comment] 2021-11-24 14:33
Hi, I am still having this issue, could anyone take a look?
Log:
`org.springframework.context.ApplicationContextException: Unable to start web server; nested exception is org.springframework.context.ApplicationContextException: Unable to start ServletWebServerApplicationContext due to missing ServletWebServerFactory bean.
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.onRefresh(ServletWebServerApplicationContext.java:163)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:577)
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:145)
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:754)
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:434)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:338)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1343)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1332)
	at com.amazonaws.serverless.sample.springboot2.Application.main(Application.java:47)
`

I change my dependency package like this
pom.xml:
` <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-tomcat</artifactId>
            <scope>compile</scope>
        </dependency>

        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-web</artifactId>






        </dependency>
`
after many tries, I still couldn't make it work.
We want to run and test it locally before deploying it to lambda.
Any helps will be appreciated.

**Comment by deki** [comment] 2021-11-24 14:37
Hmm we have working sample projects in https://github.com/awslabs/aws-serverless-java-container/tree/master/samples that you can use to compare. Or you'll share your non-working sample and we'll have a look?

**Comment by SamnnyWong** [comment] 2021-11-24 14:40
> Hmm we have working sample projects in https://github.com/awslabs/aws-serverless-java-container/tree/master/samples that you can use to compare. Or you'll share your non-working sample and we'll have a look?
yes I git clone this sample app, deploy to lambda and test run it with no problem, but if I want to run it locally (open the sample app in idea and simply click run) it prompts this error. Did i miss anyhting?

**Comment by deki** [comment] 2021-11-24 15:16
Well just remove the exclusion and then it will work. Just tried it and the sample was starting using Tomcat 9.0.50.

**Comment by SamnnyWong** [comment] 2021-11-26 14:58
I managed to recreate the issue. Since I am trying to integrate s3 into this project (as a starter code), so I click the "load gradle project" and add the dependency into build.gradle. Then I try running the app it prompts this error. Also I noticed the "edit configuration" window in idea prompts "Error: Module not specified". 
Thanks in advance.

**Comment by deki** [comment] 2021-11-26 15:03
If you are using Gradle, you have to edit the Gradle file, not the Maven POM. I suggest to try the command line tools first (e.g. by just running mvn spring-boot:run) to avoid IDE issues.
